// ===== AI Evening Plan Loader =====
// Plans are pre-generated by GitHub Action collector (data/plans/{city}.json)
// Uses Gemini API server-side → zero effort for users

async function loadCityPlan(cityName) {
  if (!cityName) return null;

  const safeName = cityName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  try {
    const resp = await fetch(`data/plans/${safeName}.json`);
    if (!resp.ok) return null;
    const data = await resp.json();
    return data.plan || null;
  } catch {
    return null;
  }
}
